### ISSUE TITLE
How to include in composer.json

### ISSUE THREAD

**Issue by zalaudekr** [WowzaMediaSystems/wse-rest-library-php#20]
How to include this package in a composer.json file ?

The following config is not working
{
  "require": {
      "php-amqplib/php-amqplib": "2.6.*",
      "WowzaMediaSystems/wse-rest-library-php": "*"
  }
}

also tried only       "wowza/wse-rest-library-php": "*"

Thanks for some help.

Regards
Raimund

**Comment by JAAulde** [comment]
Because this package was just recently modified to support composer, it is not yet registered in [Packagist](https://packagist.org), nor does it have tagged releases. As such, you'll have to install a branch (in this case `master`) directly from the repo.

**Run these commands in your terminal**

1. `cd your/project/` (where _your/project/_ is the project root directory--the directory in which your _composer.json_ lives).
2. `composer config minimum-stability dev` (this allows composer to install branches of projects instead of tagged releases)
3. `composer config prefer-stable true` (this tells composer to prefer stable package releases when they're available--recommended since you're allowing dev branches.)
4. `composer config repositories.wse-rest-library-php git git@github.com:WowzaMediaSystems/wse-rest-library-php.git` (tells composer to add this repository to the ones it looks in by default)
5. `composer require wowza/wse-rest-library-php`

Having done this, you'll notice that your _composer.json_ has all the proper entries (including a dependency of `"wowza/wse-rest-library-php": "dev-master"`), and your _vendor/_ directory now contains _wowza/_ which contains _wse-rest-library-php/_.

**Caveats**
1. Unlike other installed packages, you'll notice that the _wse-rest-library-php/_ directory is actually a clone of this repository, complete with the _.git/_ folder and all. If you're maintaining your project in such a way that you commit your _vendor/_ directory (highly discouraged by Composer), this could cause you issues.
2. Pointing directly at a branch--especially at _master_--is pretty risky. If someone commits and you update, you could receive breaking changes in your installation.

**Comment by IWriteThings** [comment]
```
{
	"repositories": [
		{
			"type":"vcs",
			"url": "https://github.com/WowzaMediaSystems/wse-rest-library-php.git"
		}
	],
	"require": {
		"wowza/wse-rest-library-php": "dev-master"
	},
	"minimum-stability": "dev"
}
```

My composer.json looks like the above and it works. You can just create that composer.json and run composer install. This is a temporary thing until we get packagist going.

**Comment by IWriteThings** [comment]
Any one cruising through can also reference ticket #24 as we are in the process of getting Wowza WSE into packagist. This will simplify deployment of this library immensely.

Thanks!

**Comment by caiblack** [comment]
Awesome!

---
Cai Black
caiblack@hotmail.com<mailto:caiblack@hotmail.com>
832-439-8134
Web Application Architect
Visual Effects (VFX) Artist


________________________________

**Comment by IWriteThings** [comment]
Closing this ticket. The readme file has been updated with a functional example of using the codebase with composer as we wait for packagist support. Thanks a bunch!
