### ISSUE TITLE
What's the correct way to create an application?

### ISSUE THREAD

**Issue by norbert-yoimo** [WowzaMediaSystems/wse-rest-library-php#38]
I'm trying to create an application like this:

```php
$settings = new \Com\Wowza\Entities\Application\Helpers\Settings();
$settings->setHost($container->getParameter('wowza_rest_api'));
$settings->setUsername($container->getParameter('wowza_user'));
$settings->setPassword($container->getParameter('wowza_password'));


$app = new \Com\Wowza\Application($settings, 'library_testapp');
$security = new \Com\Wowza\Entities\Application\SecurityConfig();
$streamConfig = new \Com\Wowza\Entities\Application\StreamConfig();
$transConfig = new \Com\Wowza\Entities\Application\TranscoderConfig();
$response = $app->create($streamConfig, $security, null, null, $transConfig);
var_dump($response);
```

However, I always get a 404, the response looks like this:

```
class stdClass#548 (4) {
  public $message =>
  string(58) "The server has not found anything matching the request URI"
  public $success =>
  bool(false)
  public $wowzaServer =>
  string(8) "4.7.2.02"
  public $code =>
  string(3) "404"
}
```

Can you point me to an example on how to use this library to create an application? My Wowza streaming engine version is 4.7.02 (build 21159).

**Comment by magkopian** [comment]
I can't tell you for sure what might be the problem, but if you add a `$settings->setDebug(true);` in your settings defining section it is going to enable the debug mode. This is going to give you the exact URI that the request is being sent to, as well as the request and response data.

**Comment by norbert-yoimo** [comment]
It was trying to use a URL like `/servers/_defaultServer_/vhosts/_defaultVHost_/applications/library_testapp`. I added a `/v2/` at the end of the `->setHost()` call, so the request goes to the v2 endpoint, but that just gives me:

```
 class stdClass#548 (4) {
  public $message =>
  string(372) "com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of boolean out of START_ARRAY token
 at [Source: (ByteArrayInputStream); line: 1, column: 1372] (through reference chain: com.wowza.wms.rest.vhosts.applications.ApplicationConfig["transcoderConfig"]->com.wowza.wms.rest.vhosts.applications.transcoder.TranscoderAppConfig["available"])"
  public $success =>
  bool(false)
  public $wowzaServer =>
  string(8) "4.7.2.02"
  public $code =>
  string(3) "400"
}
```

Is this library supposed to be used with an older/different version of streaming engine?

**Comment by magkopian** [comment]
The version you are running `4.7.2.02` is already the latest version of the WSE. This is what I also use and you shouldn't have any problems with it. Your request though needs to go to the `/v2` endpoint, otherwise you'll get a 404 like you did on your first attempt.

As for the error you get, it appears to be something related to the transcoder configuration that causes the problem. How about not defining that part at all? If you just do,

 `$response = $app->create($streamConfig, $security);`

does it appear to work?

**Comment by magkopian** [comment]
I attempted configuring nDVR and I stumbled upon the exact same problem, and it appears that it's a bug with the PHP client.

In my case, the problem was that I left the `windowDuration` property to its default value, which is an empty array if you take a look at the class definition. On the other hand, the API of the WSE expects an integer, 0 by default, and that was causing an error 400 similar to yours. After, setting the `windowDuration` to 0, the application was created successfully.

I also found a few other problems, for example the `recorders` and `store` properties were missing from the class. And also, that the default value for `storageDir` is `$\{com\.wowza\.wms\.context\.VHostConfigHome\}/dvr` while it appears that the API automatically escapes it. This results to the actual value for the storage directory to be `$\\{com\\.wowza\\.wms\\.context\\.VHostConfigHome\\}/dvr` instead of `${com.wowza.wms.context.VHostConfigHome}/dvr` as it should. I discovered this, after querying the API manually using cURL.

So, in your case, as a workaround you can try specifically setting all the properties of you `TranscoderConfig` to the correct defaults and that hopefully should fix the problem. To find out what the default values should be, you can create an application with nDVR enabled through the web interface of the WSE manager and then query the `/dvr` endpoint manually using cURL.

**Comment by IWriteThings** [comment]
Default values have been merged in. Thanks to @bagdyunovii20 for the fix for this. I am going to close this ticket and you can make a new one if his fix didn't solve your issuel

Thanks!
Aaron

**Comment by magkopian** [comment]
@IWriteThings I took a look at the pull request, and while it does fix the issue with the default values I mention on the second paragraph of my comment, the issue that I mention on the third paragraph is still there.  The default value for `storageDir` should be `${com.wowza.wms.context.VHostConfigHome}/dvr` because currently it's being double escaped and the `recorders` and `store` properties still don't exist in the class.
